services:
  ndbase:
    image: bitnami/postgresql:17.2.0
    container_name: ndbase
    restart: always
    ports:
      - "${DatabasePort}:${DatabasePort}"
    expose:
      - ${DatabasePort}
    volumes:
      - ndbase_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=${DatabaseUsername}
      - POSTGRESQL_PASSWORD=${DatabasePassword}
      - POSTGRESQL_PORT_NUMBER=${DatabasePort}
      - POSTGRESQL_DB=${DatabaseName}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresql" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ndnetwork
  # ndredis:
  #   image: bitnami/redis:latest
  #   container_name: ndredis
  #   restart: always
  #   volumes:
  #     - ndredis_data:/bitnami/redis
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - "6379:6379"
  #   command: [ "redis-server", "--appendonly", "yes" ]
  #   # healthcheck:
  #   #   test: [ "CMD", "redis-cli", "ping" ]
  #   #   interval: 30s
  #   #   timeout: 10s
  #   #   retries: 5
  #   networks:
  #     - ndnetwork

volumes:
  ndbase_data:
  ndredis_data:


networks:
  ndnetwork:
    driver: bridge
